# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/ilkay/Desktop/fpga/deneme/deneme.cache/wt [current_project]
set_property parent.project_path C:/Users/ilkay/Desktop/fpga/deneme/deneme.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/ilkay/Desktop/fpga/deneme/deneme.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Users/ilkay/Desktop/fpga/deneme/deneme.srcs/sources_1/new/sys1.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top sys1 -part xc7a35tcpg236-1


write_checkpoint -force -noxdef sys1.dcp

catch { report_utilization -file sys1_utilization_synth.rpt -pb sys1_utilization_synth.pb }
