# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/ilkay/Desktop/fpga/Encoder/Encoder.cache/wt [current_project]
set_property parent.project_path C:/Users/ilkay/Desktop/fpga/Encoder/Encoder.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/ilkay/Desktop/fpga/Encoder/Encoder.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Users/ilkay/Desktop/fpga/Encoder/Encoder.srcs/sources_1/new/encoder.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top encoder -part xc7k70tfbv676-1


write_checkpoint -force -noxdef encoder.dcp

catch { report_utilization -file encoder_utilization_synth.rpt -pb encoder_utilization_synth.pb }
